language: php

php:
  - 5.5
  - 5.6
  - 7.0

matrix:
  allow_failures:
    - php: 7.0

env:
  global:
    - DATABASE='drupal'
    - DB_USERNAME='root'
    - DB_ENCODE='utf8'
    - DOCROOT='/var/www'

mysql:
  database: $DATABASE
  username: $DB_USERNAME
  encoding: $DB_ENCODE

before_install:
  # Ensure we have the latest sources.
  - sudo apt-get -y update

  # Composer.
  - sed -i '1i export PATH="$HOME/.composer/vendor/bin:$PATH"' $HOME/.bashrc
  - source $HOME/.bashrc
  - composer self-update

  # Export display & settings originally from Marketo MA.
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

  # Drush.
  - composer global require drush/drush:~7

  # Ensure the PHP environment is ready.
  - phpenv rehash

install:
  # Basic PHP packages.
  - sudo apt-get install -y --force-yes apache2 php5-cgi libapache2-mod-php5 php5-curl php5-mysql php5-intl

  # Settings from Marketo MA.
  - sudo a2enmod rewrite
  - sudo cp -f tests/travis-ci-apache /etc/apache2/sites-available/default
  - sudo service apache2 restart
  - cd $TRAVIS_BUILD_DIR
  - export MODULE=$(basename $(pwd))
  - export MODULE_DIR=$DOCROOT/sites/all/modules/$MODULE
  - sudo chmod -R 777 /var
  - drush dl drupal --destination=/var --drupal-project-rename=www --yes
  - drush si --db-url="mysql://$DB_USERNAME@127.0.0.1/$DATABASE" -r $DOCROOT --yes
  - ln -s $TRAVIS_BUILD_DIR $MODULE_DIR
  - cd $TRAVIS_BUILD_DIR/..
  - wget http://selenium-release.storage.googleapis.com/2.47/selenium-server-standalone-2.47.1.jar
  - java -jar selenium-server-standalone-2.47.1.jar > /dev/null 2>&1 &

before_script:
  # This fixes a fail when install Drupal.
  - echo 'sendmail_path = /bin/true' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

  # Mysql might time out for long tests, increase the wait timeout.
  - mysql -e 'SET @@GLOBAL.wait_timeout=1200'

  # Settings from MArketo MA module.
  - cd $MODULE_DIR/tests
  - cp behat.yml.dist behat.yml
  - composer install
  - vendor/bin/behat features/travis-ci.feature

script:
  # Marketo MA script commands.
  - cd $MODULE_DIR/tests
  - vendor/bin/behat --tags="~travis&&~live"
